### PR TITLE
adapt docu run tests local

### PR DESCRIPTION
**Pull request by Cudok**

### CODE REVIEW

**Comment by DaJansenGit** [comment]
Thanks for this hint. But the `rm` command is only available on Linux (and MacOS, I guess?), which might be confusing for some users. Was this the only thing you had to do? I would have thought you would also need to run `git submodule update --init --recursive`...

**Comment by Cudok** [comment]
you are right, rm is not available for windows. For MacOS rm is available too.

I have done the following:
1. run submodule update --init --recursive  > get this error
2. delete this folder via rm
3. run submodule update --init --recursive again > no error

Should I add the delete command for windows?
It should be "rmdir \s test/resources"  @DaJansenGit  is this right?

**Review by DaJansenGit — APPROVED** [review]
Thanks for the enhancements!

**Comment by Cudok** [comment]
u a wellcome

**Pull request merged**
